export interface RawArticle {
  /** Stable id for dedup: hash of normalized (source, title) */
  dedupKey: string;
  source: string;
  title: string;
  url: string;
  lede: string;
  publishedAt: Date;
  /** og:image URL extracted from the publisher page; "" when unavailable */
  imageUrl: string;
}

// A cluster = one story covered by 2+ outlets
export interface IFraming {
  headlineDeltas: string[];
  toneTags: { source: string; tone: string }[];
  notableOmissions: string[];
  neutralSummary: string;
}

/** One cluster with its articles joined in, as served by the API */
export interface ClusterRecord {
  id: string;
  keyPhrase: string;
  seenAt: Date;
  framedAt: Date | null;
  framingError: string | null;
  framing: IFraming | null;
  articles: RawArticle[];
}

export interface PipelineResult {
  scraped: number;
  newArticles: number;
  clusters: number;
  framed: number;
  failed: number;
  /** True when another pipeline run held the lock and this run skipped */
  skipped?: boolean;
}

/** One row of the pipeline event log (see migration 0005). */
export interface PipelineRunRecord {
  id?: number;
  startedAt: Date;
  finishedAt: Date;
  scraped: number;
  newArticles: number;
  clusters: number;
  framed: number;
  failed: number;
  skipped: number;
  error?: string | null;
}

/** Worker bindings (generated by `wrangler types` in env.d.ts) + secrets */
export interface Env extends __BaseEnv_Env {
  GEMINI_API_KEY?: string;
  /** Fallback model tried when the primary exhausts retries */
  GEMINI_MODEL_FALLBACK?: string;
  CRON_SECRET?: string;
}
